### ISSUE TITLE
Attribute selectors is not supported

### ISSUE THREAD

**Issue by cblh** [ThisIsManta/stylus-supremacy#1]
just like `&[data-quantity*='-']` , it will throw error

```javascript
throw new Error('Found a non-string argument')
```

btw , i hope print lineno when throw error, thanks !

**Comment by ThisIsManta** [comment]
I will take care of this ASAP. Thanks for reporting!

**Comment by ThisIsManta** [comment]
Hi @cblh,

The issue has been fixed (https://github.com/ThisIsManta/stylus-supremacy/commit/8f892df89cc55a77d80030586bb968c82c6edffe). Please update your **stylus-supremacy** to version 0.1.1.

Cheers!

**Comment by cblh** [comment]
thanks very much
