### ISSUE TITLE
Lispers still haunt me

### ISSUE THREAD

**Issue by Kelin2025** [ThisIsManta/stylus-supremacy#10]
It stills happens 
v2.5.1
![image](https://user-images.githubusercontent.com/4208480/31866884-82d26cd2-b78e-11e7-855e-7cc170c75a29.png)
![image](https://user-images.githubusercontent.com/4208480/31866877-69535064-b78e-11e7-82b5-045c6f9a0926.png)

**Comment by ThisIsManta** [comment]
That's strange. I have a unit test for that case.

Are you on VS Code?

Could you try repeating this issue in https://thisismanta.github.io/stylus-supremacy/#demo and see if extra parenthesis is added.

**Comment by ThisIsManta** [comment]
You can see the number of parenthesis is exactly the same between before and after formatting (top and bottom respectively).

![screenshot_20171023-124141](https://user-images.githubusercontent.com/5592654/31873795-b19f006e-b7ef-11e7-93a4-05702cdb4b0a.png)

**Comment by Kelin2025** [comment]
> Are you on VS Code?
Yes

**Comment by ThisIsManta** [comment]
My point is that version 2.5.1 does not add extra parentheses, but it will not remove those parentheses.

This probably happens to the specific configurations. Would you mind sharing your _VS Code settings_?

The below is a GIF that I tried to replicate your issue.

![2017-10-23_17-24-50](https://user-images.githubusercontent.com/5592654/31884456-41894c26-b817-11e7-843c-83f3aeb4c762.gif)

**Comment by Kelin2025** [comment]
I have not any changed settings for _stylusSupremacy_

**Comment by Kelin2025** [comment]
Something happened and it works now :thinking: 
![image](https://user-images.githubusercontent.com/4208480/31885134-27442b3e-b7f8-11e7-9b11-9bded7eb0993.png)

**Comment by ThisIsManta** [comment]
Cool! I guess I can close this ticket. 

![Caaan do](https://res.cloudinary.com/teepublic/image/private/s--X_H3Qkss--/b_rgb:ffffff,c_limit,f_jpg,h_800,q_90,w_800/v1499696113/production/designs/1727338_1.jpg)
