### ISSUE TITLE
There is no formatter for 'stylus' files installed

### ISSUE THREAD

**Issue by jerryc127** [ThisIsManta/stylus-supremacy#105]
In 2.17.3, When I format the code, it show 'There is no formatter for 'stylus' files installed'

i install the old version 2.16.0, it is work.

**Comment by ThisIsManta** [comment]
v2.17.3 works on my end. Please be let me know how you set up your repository.

**Comment by jerryc127** [comment]
![image](https://user-images.githubusercontent.com/16351105/198931522-7e1bd583-fceb-4784-937c-41ca106fc3f2.png)
![image](https://user-images.githubusercontent.com/16351105/198931548-4d5f71f2-c507-4695-85cb-1ec74c7901e1.png)

In the right click menu, it not show the format document, when i click shift +alt + f ,  it show 'There is no formatter for 'stylus' files installed' in 2.17.3,

**Comment by Odoaker-Alaric** [comment]
Cannot find why but having the same issue. 2.16.0 works, 2.16.1 and 2.17.3 doesn't.

**Comment by SvenZhao** [comment]
same issue

**Comment by ggd543** [comment]
same issue

**Comment by GabrielF9** [comment]
> Cannot find why but having the same issue. 2.16.0 works, 2.16.1 and 2.17.3 doesn't.

same here, changing my version to 2.16.0 solved my problem

**Comment by jerryc127** [comment]
https://github.com/ThisIsManta/vscode-stylus-supremacy/issues/41

**Comment by ThisIsManta** [comment]
Ah, I screwed up the dependencies when I optimized it in the earlier version.

This should be fixed at **v2.17.4** 🙏
