### ISSUE TITLE
Format .vue files from cli

### ISSUE THREAD

**Issue by Kelin2025** [ThisIsManta/stylus-supremacy#13]
Hello again (no, lispers doesn't hunt me :smile: )  
I want to use `stylus-supremacy format` from cli to format `*.vue` files but it doesn't work  
![image](https://user-images.githubusercontent.com/4208480/33133566-410a4580-cfae-11e7-9c09-ea16ce317587.png)
Will it ever be possible?

**Comment by ThisIsManta** [comment]
Hello Anton,

I'm glad to hear that _Lips_ is no longer your problem :)

Right now, it is not possible to do so, unless you strip everything but only Stylus lines. **Stylus Supremacy** only supports Stylus files.

If there are too many files, you would want write a batch script to strip non-Stylus content, [format them](https://thisismanta.github.io/stylus-supremacy/#programming), and put everything back together.

**Comment by Kelin2025** [comment]
It's not a good solution because I want to format `<style>`'s  in all `.vue` components :cry:

**Comment by fabien-michel** [comment]
Hi, we got the same problem and we make a little script that format <style>'s parts in `.vue` files.
This is intendend to be used with pre-commit, but there is a really basic CLI support.
https://bitbucket.org/hespul/stylus-supremacy-vue

**Comment by mesqueeb** [comment]
@ThisIsManta I'd love native support for vue files! Can this issue be opened again, since it's an open request?
