### ISSUE TITLE
Unexpectedly removed ordinal arguments in mixins when mixing with named arguments

### ISSUE THREAD

**Issue by viko16** [ThisIsManta/stylus-supremacy#14]
## simple demo

```stylus
mix($left = 0, $right = 0, $top = initial)
  position absolute
  left $left
  right $right
  top $top

.test
  mix(5, $top: 6)
```

## expected

![image](https://user-images.githubusercontent.com/5064777/33409371-169b09a2-d5b6-11e7-81f7-6bb362b5ef5f.png)

http://stylus-lang.com/try.html#?code=mix(%24left%20%3D%200%2C%20%24right%20%3D%200%2C%20%24top%20%3D%20initial)%0A%20%20position%20absolute%0A%20%20left%20%24left%0A%20%20right%20%24right%0A%20%20top%20%24top%0A%0A.test%0A%20%20mix(5%2C%20%24top%3A%206)

## but, actual..

![image](https://user-images.githubusercontent.com/5064777/33409519-bfb3314a-d5b6-11e7-98b9-26b41b7ae915.png)

variables which in front of specified one `$top` has gone. 😢

**Comment by ThisIsManta** [comment]
Sorry to keep you waiting. This will be fixed in version 2.6.0.

Here's the proof:
![image](https://user-images.githubusercontent.com/5592654/33523680-421326ce-d83f-11e7-838f-8233d1ab0cc5.png)
