### ISSUE TITLE
Unexpectedly removed parenthesis of string interpolations

### ISSUE THREAD

**Issue by Rud156** [ThisIsManta/stylus-supremacy#16]
**Input:**
` height: 'calc(%s - %s)' % (default-width-height default-textarea-height);`

**Formatted Output:**
`height: 'calc(%s - %s)' % default-width-height default-textarea-height;`

**Expected Output:**
` height: 'calc(%s - %s)' % (default-width-height default-textarea-height);`

**This is incorrect as stylus converts it into:**
`height: calc((default-width-height - default-textarea-height))`
**instead of:**
`height: calc(default-width-height - default-textarea-height)`

**PS: This was when using the vscode extension**

**Comment by ThisIsManta** [comment]
Thank you for reporting the bug. I'll take a look tomorrow.

**Comment by ThisIsManta** [comment]
This is fixed in [version 2.7.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.7.0).

**Comment by Rud156** [comment]
@ThisIsManta Thanks. BTW the extension is pretty great
