### ISSUE TITLE
[Bug Report] Error when using media query with a hash getter

### ISSUE THREAD

**Issue by l1qu1d** [ThisIsManta/stylus-supremacy#18]
I have break points that are predefined in a hash object that I use with `@media` queries. I use the VsCode extension and it won't format my stylus code when using the below code. 

When I use a hash getter on the media query I get, "ERROR: Found an input node of null".

### Steps to reproduce
Example code:
`@media $display-breakpoints.md-and-up {
  }`

Example hash:
`$display-breakpoints := {
 md-and-up: "only screen and (min-width: %s)" % $grid-breakpoints.md
}`

To recreate the error just go to [https://thisismanta.github.io/stylus-supremacy/](url) and go to the section "_Try it in your browser_". Paste the media query example code above.

**Comment by ThisIsManta** [comment]
Could you give me the full example code which works in http://stylus-lang.com/try.html please?

**Comment by l1qu1d** [comment]
Here is the example code: [stylus-lang.com example](http://stylus-lang.com/try.html#?code=%24display-breakpoints%20%3D%20%7B%20%0A%20%20md-and-up%3A%20%22screen%20and%20(min-width%3A%20600px)%22%20%0A%7D%0A%0A%40media%20%24display-breakpoints.md-and-up%20%7B%20%0A%20%20.widget%20%7B%0A%20%20%20%20display%3A%20none%0A%20%20%7D%0A%7D)

**Comment by ThisIsManta** [comment]
Could you verify my fix by installing the side-load extension?
https://1drv.ms/u/s!AopesDuNO8ZogtBUIAk4nqxhI9cOAw

Instructions can be found at https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

Once the side-load extension has been installed, try repeating the issue above.

**Comment by l1qu1d** [comment]
It works if the code is in its own .styl file now, but doesn't work if you're using it in a single file app like Vuejs. 

Example: `<style lang="stylus" scoped>
    @media $display-breakpoints.md-and-up { }
</style>`

I'm using your plugin along with Vetur plugin for VsCode.

**Comment by ThisIsManta** [comment]
**Vetur** extension must be updated separately.

I'll promote a new version of **Stylus Supremacy** shortly.
For **Vetur**, please wait a bit longer as I do not control over that extension.
