### ISSUE TITLE
insertNewLineBetweenSelectors without comma

### ISSUE THREAD

**Issue by yukulele** [ThisIsManta/stylus-supremacy#19]
`insertNewLineBetweenSelectors` should not add comma (or optional)

both are valid in stylus:
```stylus
*,
*:before,
*:after
  box-sizing border-box
```
and
```stylus
*
*:before
*:after
  box-sizing border-box
```

**Comment by ThisIsManta** [comment]
How about adding a new formatting option called `insertCommaBetweenSelectors`?
This could work with `insertNewLineBetweenSelectors`.

**Comment by yukulele** [comment]
or rename it:
```
selectorsSeparator: ["newLine", "comma", "both"]
```

**Comment by ThisIsManta** [comment]
Nice idea. Do you think the below is enough?
![image](https://user-images.githubusercontent.com/5592654/35185383-2eb994ec-fe36-11e7-9e48-2cdff2bccf64.png)

**Comment by ThisIsManta** [comment]
`selectorSeparator` formatting option is added at [version 2.8.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.8.0).

Cheers!

**Comment by yukulele** [comment]
perfect, thanks!
