### ISSUE TITLE
Ignoring .stylintrc

### ISSUE THREAD

**Issue by aharris** [ThisIsManta/stylus-supremacy#2]
Atom Plugin:

In the root of my project I have .stylintrc with the following:

`{
  "insertColons": false,
  "insertSemicolons": false,
  "insertBraces": false
}
`

However all of these are still applied. 

`
.foo {
	display: none;
}
`

**Comment by ThisIsManta** [comment]
Hi @aharris, thanks for your interest in Stylus Supremacy.

I believe you have misunderstood the **formatting options** (`insertColons`, `insertBraces` and so on) with **Stylint rules** (`colons`, `braces` and so on). Content in *.stylintrc* file should look like this:
```
{
  "colons": "never",
  "braces": "never"
}
```
Please refer to [the formatting-option and Stylint-rule conversion table](https://thisismanta.github.io/stylus-supremacy/#stylint-rules). Basically, you have to use the **TEAL column** in *.stylintrc*.
Let me know if I can improve our documentation web site so it prevents others from further confusion.

Cheers!

**Comment by aharris** [comment]
Thanks for that. I missed this mapping.
