### ISSUE TITLE
Formatting '@import x if (y);'

### ISSUE THREAD

**Issue by animify** [ThisIsManta/stylus-supremacy#20]
Using the default options:

`@import -fn if (exists(-fn));`

gets formatted to:

```
@import -fn;
 if (exists(-fn));
```

Any ideas?

**Comment by ThisIsManta** [comment]
This is fixed at [version 2.8.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.8.0).

Cheers!

**Comment by animify** [comment]
Super! Cheers 👍
