### ISSUE TITLE
how to exclude stylus-supremacy [vs-code] to autofix files

### ISSUE THREAD

**Issue by D4NH** [ThisIsManta/stylus-supremacy#23]
Using .stylintrc with the following exclude property doesn't ignore the autofix when saving the file.

`
{
    "exclude": ["vendor/assets/style/variables/**/*"]
}
`

Is there any other way to ignore autofix files when open and saving them?
Also using the built-in `editor.formatOnSave` setting, maybe it's not possible?

**Comment by ThisIsManta** [comment]
May I see your whole stylintrc file?

**Comment by D4NH** [comment]
```
{
  "reporter": "stylint-stylish",
  "noImportant": true,
  "semicolons": "never",
  "brackets": "never",
  "colons": "always",
  "commaSpace": "always",
  "commentSpace": "always",
  "duplicates": "true",
  "efficient": "always",
  "zeroUnits": "always",
  "exclude": ["vendor/mo-ux/mijnoverheid-style-bundle/Resources/assets/style/variables/**/*"],
  "leadingZero": "always",
  "namingConvention": "lowercase-dash",
  "semicolons": "never",
  "sortOrder": "alphabetical"
}
```

**Comment by ThisIsManta** [comment]
What if a user manually run **Format Document** on the file that is in ignored pattern?

**Comment by ThisIsManta** [comment]
Hmm, I guess it's all or nothing. I cannot make the ignored (`exclude`) files get manually formatted.

**Comment by ThisIsManta** [comment]
Starting from **Stylus Supremacy** v2.9.0, it recognizes `exclude` in _stylintrc_ file or `ignoreFiles` formatting option. See also https://thisismanta.github.io/stylus-supremacy/#option-ignore-files

Cheers!

**Comment by D4NH** [comment]
This is great. Thanks!
