### ISSUE TITLE
feature_request(config): support YAML configuration format

### ISSUE THREAD

**Issue by Kristinita** [ThisIsManta/stylus-supremacy#31]
### 1. Summary

It would be nice, if Supermacy will support YAML configuration files. `supermacy.yaml` for example.

### 2. Argumentation

I think, JSON — bad idea. Main reason — I can't write comments, why I use those or other options. Another arguments:

+ [**JSON as configuration files: please don't**](https://arp242.net/weblog/json_as_configuration_files-_please_dont)

### 3. Related issues:

+ [**Markdownlint**](https://github.com/DavidAnson/markdownlint/issues/118)
+ [**CoffeeLint**](https://github.com/clutchski/coffeelint/issues/638)
+ [**Stylint**](https://github.com/SimenB/stylint/issues/434)

Thanks.

**Comment by Kristinita** [comment]
> I will add support for YAML later.

Thanks, we wait it.

**Comment by Kristinita** [comment]
> Regarding your concern with JSON as a configuration file, JSON5 exists. In fact, you can write Stylus Supremacy option files in JSON with comments now.

Supremacy and Stylint use one configuration file — `.stylintrc`. I use Stylint via Grunt — [**grunt-stylint**](https://github.com/xdissent/grunt-stylint). Grunt parser doesn't support comments in JSON file.

Thanks.

**Comment by ThisIsManta** [comment]
You can pass YAML as a formatting option file by writing the command `stylus-supremacy -p options.yml` at version 2.11. Just make sure that the file has `.yml` or `.ymal` extension.

Cheers!
