### ISSUE TITLE
question(options): default settings

### ISSUE THREAD

**Issue by Kristinita** [ThisIsManta/stylus-supremacy#32]
### 1. Summary

I don't understand, why the default settings for Stylus Supermacy are as they are at this time.

Do they comply with any standard for writing Stylus code?

### 2. Example

my `SashaStylus.styl` file:

```stylus
.SashaClass
    color red
```

I run in a terminal:

    stylus-supremacy format SashaStylus.styl

Result:

```stylus
.SashaClass {
        color: red;
}

```

Braces, colon, semicolon? Are these exactly Stylus, not CSS standards?

### 3. Answer to possible answer

> You can configure Stylus Supermacy as you want

It would be nice, if we will have standard.

> When we learn a new language, we usually begin to code in a specific style. In most cases, we’ll write in a style that we want, not one that has been suggested to us. But once we start to code using a particular style, like a spoken language dialect, it will become second nature — we’ll use that style in everything we create. Such a style might include the conventions we use to name variables and functions ($userName, $username or $user_name for example), and how we comment our work. Any style should ensure that we can read our code easily.

> However, what happens when we start to code bigger projects and introduce additional people to help create a large application? Conflicts in the way you write your code will most definitely appear.

More details:

+ [**Why You Need Coding Standards**](https://www.sitepoint.com/coding-standards/)

Thanks.

**Comment by ThisIsManta** [comment]
I believe you have noticed that the default **Stylus Supremacy** format is exactly like CSS. This is my intention to eliminate the learning curve for Stylus newbies.

My company is currently using Stylus, and yes, we do have a specific `.stylintrc` file, which **Stylus Supremacy** picks up and format accordingly.
