### ISSUE TITLE
feature_request(editor): Sublime Text support

### ISSUE THREAD

**Issue by Kristinita** [ThisIsManta/stylus-supremacy#33]
### 1. Summary

It would be nice, if Stylus Supermacy will be integrated as Sublime Text plugin.

### 2. Argumentation

Sublime Text is popular text editor. Sublime Text users will be glad Sublime Text Supermacy plugin.

+ [**Most Popular Developer Environments**](https://insights.stackoverflow.com/survey/2017#technology-most-popular-developer-environments-by-occupation)

![Web statistics](https://i.imgur.com/U0lzANP.png)

### 3. Resources

+ [**Sublime Text 3 API**](https://www.sublimetext.com/docs/3/api_reference.html)
+ [**Writing Sublime Text Plugins book**](https://leanpub.com/writing-sublime-plugins)

Thanks.

**Comment by ThisIsManta** [comment]
Sorry, but I am not a big fan of Sublime Text. Since Stylus Supremacy is MIT licensed, I would be glad if you could develop the plug-in yourself.
