### ISSUE TITLE
question(config): Supermacy options in .stylintrc

### ISSUE THREAD

**Issue by Kristinita** [ThisIsManta/stylus-supremacy#34]
### 1. Summary

I can't find, how I can use Stylus Supermacy options, if I use `.stylintrc`.

### 2. Configuration

`SashaSupermacy.styl`:

```stylus
.SashaFirst
.SashaSecond {
    color: red
}

```

`supermacy.json`:

```json
{
    "stylusSupremacy.selectorSeparator": "\n"
}

```

`.stylintrc`:

```json
{
    "blocks": "never",
    "brackets": "never",
    "colons": "never",
    "colors": "always",
    "commaSpace": "always",
    "commentSpace": "always",
    "cssLiteral": "always",
    "depthLimit": 4,
    "duplicates": "always",
    "efficient": "always",
    "exclude": [],
    "extendPref": "@extend",
    "globalDupe": "always",
    "groupOutputByFile": "always",
    "indentPref": false,
    "leadingZero": "never",
    "maxErrors": "never",
    "maxWarnings": "never",
    "mixed": "always",
    "namingConvention": false,
    "namingConventionStrict": "always",
    "none": "never",
    "noImportant": "always",
    "parenSpace": "never",
    "placeholder": "always",
    "prefixVarsWithDollar": "never",
    "quotePref": "double",
    "semicolons": "never",
    "sortOrder": false,
    "stackedProperties": "always",
    "trailingWhitespace": "never",
    "universal": "never",
    "valid": false,
    "zeroUnits": "never",
    "zIndexNormalize": 100
}

```

### 3. Expected behavior

I want convent `SashaSupermacy.styl` to:

```stylus
.SashaFirst
.SashaSecond
    color red

```

I hate any extra colons, braces, commas and so on.

### 4. Actual behavior

**If**:

    stylus-supremacy format SashaSupermacy.styl -r -p supermacy.json

```stylus
.SashaFirst
.SashaSecond {
    color: red;
}

```

**else**:

    stylus-supremacy format SashaSupermacy.styl -r -p .stylintrc

```stylus
.SashaFirst, .SashaSecond
    color red

```

### 5. Not helped

1. Place `"stylusSupremacy.selectorSeparator": "\n"` **or** `"selectorSeparator": "\n"` to `.stylintrc`.
1. `stylus-supremacy format SashaSupermacy.styl -r -p .stylintrc supermacy.json` **or** `stylus-supremacy format SashaSupermacy.styl -r -p .stylintrc -p supermacy.json` commands. I get `ParseError` in terminal.
1. I can't find equivalent of `"stylusSupremacy.selectorSeparator": "\n"` in [**Stylint options**](https://www.npmjs.com/package/stylint#the-config-approach).

Thanks.

**Comment by ThisIsManta** [comment]
Nope, there's no equivalent of `selectorSeparator` in stylintrc file.

**Comment by ThisIsManta** [comment]
Closed due to no activities.

**Comment by Kristinita** [comment]
How I can solved this problem?

Thanks.
