### ISSUE TITLE
use of null yields "Found unkown object"

### ISSUE THREAD

**Issue by undefinederror** [ThisIsManta/stylus-supremacy#36]
Hi,
May I ask why stylus-supremacy does not support `null`?

![image](https://user-images.githubusercontent.com/8209966/43094719-094adbe4-8eb4-11e8-9437-d932f8b8b73f.png)

The same snippet works in [the official stylus online editor](http://stylus-lang.com/try.htm)

![image](https://user-images.githubusercontent.com/8209966/43094766-2a3641f4-8eb4-11e8-8655-eba4fab8111e.png)

It doesn't seem right. Is there any configuration option to prevent this error from being thrown?

Thank you

**Comment by ThisIsManta** [comment]
This is definitely a bug. I'll fix it soon. Please bear with me.

**Comment by undefinederror** [comment]
thank you!

**Comment by ThisIsManta** [comment]
This has been fixed at version [2.12.1](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.12.1).

Cheers!

**Comment by undefinederror** [comment]
outstanding :1st_place_medal:
