### ISSUE TITLE
Insert New Line Settings Not Working

### ISSUE THREAD

**Issue by themostcolm** [ThisIsManta/stylus-supremacy#37]
in my .stylsrc file I have included the two following lines:

```
  "insertNewLineAroundBlocks": false,
  "insertNewLineAroundOthers": false,
```

Other settings are working and I can change them and save and I will see the changes reflected immediately in my .styl file, but not the two settings above.

**Comment by ThisIsManta** [comment]
Have you tried https://thisismanta.github.io/stylus-supremacy/ yet?

**Comment by ThisIsManta** [comment]
I'm closing this issue as it works fine on my end.

**Comment by themostcolm** [comment]
I’m sorry, I have had a busy week. Yes, that is what I formatted my Ike after, and it was not working. Others settings did though, such as “brackets”: true

**Comment by ThisIsManta** [comment]
Would you mind sharing your Stylus code and its expectation, please?

**Comment by themostcolm** [comment]
```
.subheading {
	padding-top: 1rem
}

.index-heading {
	color: purple
	padding-top: 5rem
	text-align: center
}

.cards {
	display: flex
	flex-wrap: wrap
	justify-content: center
	padding-top: 3rem
}

```

On the playground link you shared, it comes out to:

```
.subheading {
  padding-top: 1rem
}
.index-heading {
  color: purple
  padding-top: 5rem
  text-align: center
}
.cards {
  display: flex
  flex-wrap: wrap
  justify-content: center
  padding-top: 3rem
}
```

Which is what I would expect to happen

**Comment by ThisIsManta** [comment]
You want it to be like the below after formatting. Plus, you only have styling rules in `.stylintrc` file. Am I correct?
```
.subheading {
	...
}

.index-heading {
	...
}

.cards {
	...
}
```
