### ISSUE TITLE
Minus sign before variable or funciton will be remove space between them

### ISSUE THREAD

**Issue by cblh** [ThisIsManta/stylus-supremacy#4]
Minus sign before variable or funciton will be remove space between them

`
left: - px2rem(9px)
`
will be
`
left: -px2rem(9px)
`

it  causes variable or function to not be recognized

**Comment by ThisIsManta** [comment]
Thank you for reporting this.

I will work on this promptly. Please bear with me.

**Comment by ThisIsManta** [comment]
Hello @cblh,

How about wrapping the variable in a pair of parenthesis? This would be more explicit _(than adding a white-space)_ that you want to invert the value from the variable.

![image](https://user-images.githubusercontent.com/5592654/28922135-28765ca2-7883-11e7-8b6d-2c3bc505422c.png)

Or, I can create a new option `insertParenthesisAroundVariableNegation` (`false` by default).

Let me know your thought.

**Comment by ThisIsManta** [comment]
Please upgrade to [version 1.6.2](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v1.6.2). Thanks!
