### ISSUE TITLE
vue component bug in vscode 

### ISSUE THREAD

**Issue by wangxdmm** [ThisIsManta/stylus-supremacy#42]
when I use two tags like 
```html
<style lang="stylus" rel="stylesheet/stylus">
styluscode a
</style>
<style scoped lang="stylus" rel="stylesheet/stylus">
styluscode b
</style>
```
when I formate the code `styluscode b` will be replaced by `styluscode a`..

I don't how to solve this problem
I am looking forward to your reply ~v~

**Comment by ThisIsManta** [comment]
I believe this is the limitation of **Vetur** extension and has nothing to do with **Stylus Supremacy**. I remember someone raised the same issue before, please find it in **Vetur** repository.

Thanks!

**Comment by wQueryLoveMm** [comment]
@ThisIsManta  Thanks for your reply ~ That's the limitation of `Vetur`
 If someone come across the same problem
[https://github.com/vuejs/vetur/issues/430](url)

**Comment by octref** [comment]
Would be fixed by https://github.com/vuejs/vetur/pull/1174.
