### ISSUE TITLE
Check mode

### ISSUE THREAD

**Issue by pesterhazy** [ThisIsManta/stylus-supremacy#53]
Is there a way to run the tool in "check" mode?

It should return exit status 0 if all files are already formatted according to the guidelines, exit status 1 otherwise.

This would allow operation in CI jobs to make sure that only files that are properly formatted can be merged.

**Comment by ThisIsManta** [comment]
Done at [v2.14.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.14.0)

See usage example at the second-to-last paragraph in [the official doc](https://thisismanta.github.io/stylus-supremacy/#command-line)
