### ISSUE TITLE
Add a marker to ignore a line when formatting

### ISSUE THREAD

**Issue by Cactusbone** [ThisIsManta/stylus-supremacy#57]
Sometimes we have specific fixes for internet explorer where unit is required after a 0 
https://github.com/philipwalton/flexbugs#flexbug-4

In that particular case we want to keep `flex 1 1 0px`
so adding `// @stylus-supremacy-ignore` on the previous line (or the line itself) would allow us to ignore rules when needed (inspired from https://www.npmjs.com/package/stlint#ignore-errors)

**Comment by ThisIsManta** [comment]
What was your configs? Did you turn on [`alwaysUseZeroWithoutUnit`](https://thisismanta.github.io/stylus-supremacy/#option-always-use-zero-without-unit)?

**Comment by Cactusbone** [comment]
Yes, usually we want zero without unit, but in the flex case, the unit must remain, so having a way to ignore a line when formatting would be useful

**Comment by ThisIsManta** [comment]
Personally, I want Stylus Supremacy formatter to work out of the box, without having to handle exceptional cases like `flex-basis`.
I'm thinking of keeping the unit for `flex-basis` so it will not break IE.

**Comment by ThisIsManta** [comment]
This will be fixed in v2.14.2 or newer.

![image](https://user-images.githubusercontent.com/5592654/81164999-6c7cdc80-8fbb-11ea-9003-b02edfb26d20.png)
