### ISSUE TITLE
Not preserving lines around custom @-rules

### ISSUE THREAD

**Issue by 01010101lzy** [ThisIsManta/stylus-supremacy#60]
Plugin version: 2.14.0 (tested in browser and VSCode plugin)

When formatting the following code in Stylus Supremacy:

```styl
@lost gutter 24px
@lost flexbox flex
default-font = 'Sarasa UI SC'
```

We get the following result (with default settings):

```styl
@lost gutter 24px;@lost flexbox flex;default-font = 'Sarasa UI SC';
```

![图片](https://user-images.githubusercontent.com/10259119/70604641-eccd2a80-1c33-11ea-98ac-253821d2babc.png)

Formatting without semicolons makes things worse:

```styl
@lost gutter 24px@lost flexbox flexdefault-font = 'Sarasa UI SC'
```

Expected output is the same with input (with semicolons).

**Comment by ThisIsManta** [comment]
This will be fixed in v2.14.2 or newer.
