### ISSUE TITLE
warning: expected never to be one of the defined values at "sortProperties".

### ISSUE THREAD

**Issue by Shen-Yu** [ThisIsManta/stylus-supremacy#62]
### When i right click and format in my stylus file ，it's not work...and warning following text.
![image](https://user-images.githubusercontent.com/13065982/72254426-fa187300-363e-11ea-9617-3b9bdc019fe1.png)

**Comment by ThisIsManta** [comment]
Would you show me your VSCode `settings.json` and `.stylintrc` (if any)?

**Comment by Shen-Yu** [comment]
it's been resolved.
