### ISSUE TITLE
Problem to format styl in vscode (There is no formatter for 'stylus' files installed)

### ISSUE THREAD

**Issue by renanveroneze** [ThisIsManta/stylus-supremacy#67]
When I try to format the code: (⌘ + shift + p) -> Format Document
I get this message: **There is no formatter for 'stylus' files installed.**

<img width="1408" alt="Screen Shot 2020-05-07 at 02 07 53" src="https://user-images.githubusercontent.com/2257531/81257092-c6f05a00-9008-11ea-8aa5-4e7394749e25.png">

**Comment by ThisIsManta** [comment]
Would you show me this page?

![image](https://user-images.githubusercontent.com/5592654/81257756-4bb99300-905e-11ea-8c58-39f899195c0c.png)

**Comment by renanveroneze** [comment]
I've tried uninstalling and installing again, but it didn't work ...

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2257531/81264315-919f3880-9017-11ea-8a0e-b27a1972f38c.png">

**Comment by ThisIsManta** [comment]
Can I see your User `settings.json` and possibly Workspace `.vscode/settings.json`?

![image](https://user-images.githubusercontent.com/5592654/81272581-da86d980-9077-11ea-85bc-0a6b86050185.png)

**Comment by renanveroneze** [comment]
I uploaded the files to the gist...
https://gist.github.com/renanveroneze/2875958a6c6667b68c74b793c339a9ac

**Comment by farengeyt451** [comment]
I have same problem after 2.14.0 update. Rolled back to the previous version - everything works

**Comment by ThisIsManta** [comment]
OK. I'll take a look soon.

**Comment by mixmyxxe** [comment]
Same here. 🤕

**Comment by ThisIsManta** [comment]
This should be fixed in v2.14.3. Please upgrade and try again.

It was my stupidity to not include `node_modules` when publishing the extension.
Sorry for the inconvenient!

**Comment by renanveroneze** [comment]
Thank you very much, this extension is the best of all, I can't live without it ...

Hugs ;D
