### ISSUE TITLE
Need keep braces aroung expressions

### ISSUE THREAD

**Issue by dmitriy-lodyanov** [ThisIsManta/stylus-supremacy#9]
When we write any expression:
.test
  width (100% / some) // some is a variable
After fixing:
.test
  width 100% / some
And there we lose expression, stylus will paste 100% / some as is, and it's a bug

**Comment by ThisIsManta** [comment]
Thank you for reporting this bug. Spare me a weekend to fix this.

**Comment by dmitriy-lodyanov** [comment]
Thank you for development this awesome formatter
I will use it after all

**Comment by ThisIsManta** [comment]
This is fixed in version 2.4.1. Cheers!

**Comment by dmitriy-lodyanov** [comment]
Awesome!

**Comment by zhanziyang** [comment]
Hi, I'm using v2.5.0 and the issue still exists.

**Comment by ThisIsManta** [comment]
Interesting. Let me have a look.

**Comment by zhanziyang** [comment]
Thank you.
